# Generated by Django 2.0 on 2017-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_email',
            field=models.EmailField(max_length=50),
        ),
    ]
